Make edit async
CoreyHayward/PowerToys-Run-ClipboardManager pull request #14
Opened 2024-11-14 08:21 UTC by 8LWXpg

The refactor removes async part in `EditAsync`, so it's executed synchronously and PowerToys Run UI will block the edit window.

This PR also removes `Microsoft.Windows.SDK.NET.dll` and `WinRT.Runtime.dll` as they are already included in PowerToys, and only preserve `Paster.exe` in the `Paster` directory.

2024-11-18 16:15 UTC, CoreyHayward requested changes

2024-11-18 16:15 UTC, CoreyHayward commented on Community.PowerToys.Run.Plugin.ClipboardManager/Main.cs
> +                        static async Task EditAsync(Result selectedResult, PluginInitContext context)
`PluginInitContext context` is unused and can be removed
- [ ] Remove unused parameter

2024-11-18 16:15 UTC, CoreyHayward commented on Community.PowerToys.Run.Plugin.ClipboardManager/Main.cs
> +                            await Task.Run(() => {
Could you just explain the following to me a bit more:

> so it's executed synchronously and PowerToys Run UI will block the edit window.

 What is it exactly you are trying to achieve? Locking the PT Run window?
The `EditAsync` method is still executed asyncronously because of your discard assignment on line 213 so nothing is really locked as a result of this change.

2024-11-19 04:45 UTC, 8LWXpg commented on Community.PowerToys.Run.Plugin.ClipboardManager/Main.cs
> +                            await Task.Run(() => {
In short, marking function with `async` and wrap the return in `Task<>` does not make the function async unless there's `await` in it (dotnet will catch this and throw a warning). So, the function is actually synchronous after `await` is removed at a91e5ff.

2024-11-19 07:41 UTC, merged